import Navbar from '@/src/Components/Navbar/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import Foter from '@/src/Components/Footer/Foter'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Olma',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <Foter />
      </body>
    </html>
  )
}
